package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> bubbleSort(T[] arr) {
        List<SortEvent<Integer>> arrLst = new ArrayList<>();
        for (int i = arr.length - 1; i > 0; i--) {
            for (int j = 0; j < i; j++) {
                arrLst.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    swap(arr, j, j + 1);
                    arrLst.add(new SwapEvent<>(j, j + 1));
                }
            }
        }
        return arrLst;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> selectionSort(
            T[] arr) {
        List<SortEvent<Integer>> arrLst = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            for (int j = i; j < arr.length; j++) {
                arrLst.add(new CompareEvent<>(j, i));
                if (arr[j].compareTo(arr[i]) < 0) {
                    swap(arr, i, j);
                    arrLst.add(new SwapEvent<>(j, i));
                }
            }
        }
        return arrLst;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> insertionSort(
            T[] arr) {
        List<SortEvent<Integer>> arrLst = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            int minIndex = i;
            for (int j = i; j < arr.length; j++) {
                arrLst.add(new CompareEvent<>(minIndex, j));
                if (arr[minIndex].compareTo(arr[j]) > 0) {
                    minIndex = j;
                }
            }
            arrLst.add(new SwapEvent<>(i, minIndex));
            swap(arr, i, minIndex);
        }
        return arrLst;
    }

    private static <T extends Comparable<? super T>> void merge(T[] arr, int startIndex, int midIndex,
            int endIndex, List<SortEvent<T>> arrLst) {
        // arrLst.add(new CopyEvent<Integer>(midIndex, endIndex, null));

        T[] copyArr = Arrays.copyOfRange(arr, startIndex, endIndex);
        // System.arraycopy(arr, startIndex, temp, startIndex, endIndex - startIndex);

        int i = 0;
        int j = midIndex - startIndex;
        int k = startIndex;

        int leftEnd = midIndex - startIndex;
        int rightEnd = endIndex - startIndex;

        // Merge the two halves back into the original array (arr)
        while (k < endIndex) {

            // Check if the left half is exhausted
            if (i >= leftEnd) {
                T val = copyArr[j];
                arrLst.add(new CopyEvent<T>(j + startIndex, k, copyArr[j]));
                arr[k] = val;
                j++;
            }
            // Check if the right half is exhausted
            else if (j >= rightEnd) {
                T val = copyArr[i];
                arrLst.add(new CopyEvent<T>(i + startIndex, k, copyArr[i]));
                arr[k] = val;
                i++;
            }
            // Compare elements from both halves
            else if (copyArr[i].compareTo(copyArr[j]) <= 0) {
                arrLst.add(new CompareEvent<>(i + startIndex, j + startIndex));
                T val = copyArr[i];
                arrLst.add(new CopyEvent<T>(i + startIndex, k, copyArr[i]));
                arr[k] = val;
                i++;
            } else {
                arrLst.add(new CompareEvent<>(i + startIndex, j + startIndex));
                T val = copyArr[j];
                arrLst.add(new CopyEvent<T>(j + startIndex, k, copyArr[j]));
                arr[k] = val;
                j++;
            }
            k++;
        }
    }

    public static <T extends Comparable<? super T>> void mergeSortHelper(T[] arr, int startIndex,
            int endIndex, List<SortEvent<T>> arrLst) {

        if ((endIndex - startIndex) <= 1) {
            return;
        }
        int midIndex = startIndex + (endIndex - startIndex) / 2;

        mergeSortHelper(arr, startIndex, midIndex, arrLst);
        mergeSortHelper(arr, midIndex, endIndex, arrLst);
        merge(arr, startIndex, midIndex, endIndex, arrLst);
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(
            T[] arr) {
        List<SortEvent<T>> arrLst = new ArrayList<>();
        mergeSortHelper(arr, 0, arr.length, arrLst);
        return arrLst;
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> quickSort(T[] arr) {
        // TODO: fill me in!
        return null;
    }

// cant be bothered of doing it rn



    public static <T extends Comparable<? super T>> void eventSort(T[] ogArr, List<SortEvent<T>> arrList) {
        int i = 0;
        while(i < arrList.size()){
            if(arrList.get(i).isEmphasized()){
                arrList.get(i).apply(ogArr);
            }
        }
        return;
    }
}
